---
abstract: 'The great new Nagios::Plugin::OverHTTP!'
author:
  - 'Douglas Christopher Wilson <doug@somethingdoug.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.85'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nagios-Plugin-OverHTTP
no_index:
  directory:
    - inc
    - t
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.01
