---
abstract: 'Nagios plugin to check over the HTTP protocol.'
author:
  - 'Douglas Christopher Wilson <doug@somethingdoug.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.85'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nagios-Plugin-OverHTTP
no_index:
  directory:
    - inc
    - t
requires:
  Getopt::Long::Descriptive: 0.074
  Moose: 0.74
  MooseX::StrictConstructor: 0.08
  Scalar::Util: 1.19
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
